### ISSUE TITLE
DOOR 是否等于 Jacob1's mod 中的 PINV ？

### ISSUE THREAD

**Issue by git123hub** [HydroH/The-Powder-Toy#22]
https://github.com/HydroH/The-Powder-Toy/blob/dev-Iodizon/src/simulation/elements/DOOR.cpp
https://github.com/jacob1/The-Powder-Toy/blob/c%2B%2B/src/simulation/elements/PINV.cpp

**Comment by HydroH** [comment]
差不多，PINV出之前社区里一直有这个想法 很多mod都实现了
